# Reading Data

In [47]:
#importing libraries
import pandas as pd
import numpy as np
import glob
import os

In [48]:
#monthly flow rate data from 1925-2924
flow_monthly = pd.read_csv("monthly_flow_rate_fraser.csv", skiprows = 1)
flow_monthly.head(15)

,ID,PARAM,TYPE,Year,Jan,SYM,Feb,SYM.1,Mar,SYM.2,...,SYM.7,Sep,SYM.8,Oct,SYM.9,Nov,SYM.10,Dec,SYM.11,Mean
0,08MF005,1,1,1912,NaN,NaN,NaN,NaN,485.0,NaN,...,NaN,2160.0,NaN,1530.0,NaN,1060.0,NaN,761.0,NaN,NaN
1,08MF005,1,1,1913,516.0,NaN,710.0,NaN,570.0,NaN,...,NaN,3930.0,NaN,1760.0,NaN,1010.0,NaN,736.0,NaN,2810.0
2,08MF005,1,1,1914,1050.0,NaN,787.0,NaN,906.0,NaN,...,NaN,2140.0,NaN,1970.0,NaN,1760.0,NaN,1080.0,NaN,2920.0
3,08MF005,1,1,1915,886.0,NaN,749.0,NaN,806.0,NaN,...,NaN,1690.0,NaN,1270.0,NaN,1190.0,NaN,585.0,NaN,2270.0
4,08MF005,1,1,1916,543.0,NaN,945.0,NaN,780.0,NaN,...,NaN,2350.0,NaN,1620.0,NaN,1040.0,NaN,643.0,NaN,2510.0
5,08MF005,1,1,1917,589.0,NaN,543.0,NaN,482.0,NaN,...,NaN,2130.0,NaN,2100.0,NaN,1940.0,NaN,1590.0,NaN,2710.0
6,08MF005,1,1,1918,1660.0,NaN,1140.0,NaN,964.0,NaN,...,NaN,2570.0,NaN,1650.0,NaN,1180.0,NaN,837.0,NaN,3060.0
7,08MF005,1,1,1919,668.0,NaN,584.0,NaN,497.0,NaN,...,NaN,2420.0,NaN,1430.0,NaN,1320.0,NaN,1160.0,NaN,2640.0
8,08MF005,1,1,1920,1010.0,NaN,834.0,NaN,648.0,NaN,...,NaN,3130.0,NaN,3310.0,NaN,1860.0,NaN,1200.0,NaN,3270.0
9,08MF005,1,1,1921,935.0,NaN,899.0,NaN,824.0,NaN,...,NaN,2710.0,NaN,2700.0,NaN,1940.0,NaN,1360.0,NaN,3210.0
10,08MF005,1,1,1922,908.0,NaN,677.0,NaN,590.0,NaN,...,NaN,2510.0,NaN,2300.0,NaN,1310.0,NaN,1170.0,NaN,2620.0
11,08MF005,1,1,1923,906.0,NaN,674.0,NaN,612.0,NaN,...,NaN,2500.0,NaN,1290.0,NaN,939.0,NaN,841.0,NaN,2590.0
12,08MF005,1,1,1924,579.0,NaN,907.0,NaN,715.0,NaN,...,NaN,3110.0,NaN,1950.0,NaN,1310.0,NaN,1230.0,NaN,2710.0
13,08MF005,1,1,1925,869.0,NaN,780.0,NaN,702.0,NaN,...,NaN,2360.0,NaN,1140.0,NaN,894.0,NaN,1700.0,NaN,2730.0
14,08MF005,1,1,1926,1240.0,NaN,857.0,NaN,939.0,NaN,...,NaN,1580.0,NaN,1450.0,NaN,1270.0,NaN,882.0,NaN,2250.0

In [49]:
#monthly temperature data from 1925 - 2007
temp_monthly_1925_2007 = pd.read_csv("monthly_1925-2007.csv")
temp_monthly_1925_2007.head()

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Mean Max Temp (°C),Mean Max Temp Flag,Mean Min Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow Grnd Last Day (cm),Snow Grnd Last Day Flag,Dir of Max Gust (10's deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-123.12,49.3,VANCOUVER HARBOUR CS,1108446,1925-01,1925,1,NaN,NaN,NaN,...,NaN,M,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN
1,-123.12,49.3,VANCOUVER HARBOUR CS,1108446,1925-02,1925,2,NaN,NaN,NaN,...,NaN,M,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN
2,-123.12,49.3,VANCOUVER HARBOUR CS,1108446,1925-03,1925,3,NaN,NaN,NaN,...,NaN,M,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN
3,-123.12,49.3,VANCOUVER HARBOUR CS,1108446,1925-04,1925,4,NaN,NaN,NaN,...,NaN,M,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN
4,-123.12,49.3,VANCOUVER HARBOUR CS,1108446,1925-05,1925,5,NaN,NaN,NaN,...,NaN,M,NaN,M,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
# Get all files that start with 'daily_20'
daily_files = glob.glob("daily_20*.csv")
daily_files

['daily_2020.csv',
 'daily_2008.csv',
 'daily_2009.csv',
 'daily_2021.csv',
 'daily_2023.csv',
 'daily_2022.csv',
 'daily_2019.csv',
 'daily_2024.csv',
 'daily_2018.csv',
 'daily_2015.csv',
 'daily_2014.csv',
 'daily_2016.csv',
 'daily_2017.csv',
 'daily_2013.csv',
 'daily_2012.csv',
 'daily_2010.csv',
 'daily_2011.csv']

In [51]:
#reading and merging all daily temperature data files from 2008 - 2024
daily_list = []
for file in daily_files:
    df = pd.read_csv(file)
    daily_list.append(df)
temp_daily_2008_2024 = pd.concat(daily_list, ignore_index=True)
temp_daily_2008_2024.head()

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-123.12,49.3,VANCOUVER HARBOUR CS,1108446,2020-01-01,2020,1,1,NaN,12.4,...,NaN,NaN,NaN,M,NaN,NaN,NaN,M,NaN,M
1,-123.12,49.3,VANCOUVER HARBOUR CS,1108446,2020-01-02,2020,1,2,NaN,7.2,...,NaN,NaN,0.6,NaN,NaN,NaN,NaN,M,NaN,M
2,-123.12,49.3,VANCOUVER HARBOUR CS,1108446,2020-01-03,2020,1,3,NaN,11.2,...,NaN,NaN,4.9,NaN,NaN,NaN,NaN,M,NaN,M
3,-123.12,49.3,VANCOUVER HARBOUR CS,1108446,2020-01-04,2020,1,4,NaN,9.3,...,NaN,NaN,2.5,NaN,NaN,NaN,NaN,M,NaN,M
4,-123.12,49.3,VANCOUVER HARBOUR CS,1108446,2020-01-05,2020,1,5,NaN,7.4,...,NaN,NaN,1.4,NaN,NaN,NaN,NaN,M,NaN,M

In [52]:
print("Flow monthly shape:", flow_monthly.shape)
print("Monthly temp shape:", temp_monthly_1925_2007.shape)
print("Daily temp shape:", temp_daily_2008_2024.shape)

Flow monthly shape: (224, 29)
Monthly temp shape: (986, 29)
Daily temp shape: (6210, 31)

# Cleaning data

In [53]:
#dropping unwanted columns from flow rate data
flow_clean = flow_monthly.drop(columns=[' ID', 'TYPE', 'Mean'])
flow_clean = flow_clean.loc[:, ~flow_clean.columns.str.contains('SYM')]
flow_clean = flow_clean[(flow_clean['Year'] >= 1925) & (flow_clean['Year'] <= 2024)]
flow_clean.head()

,PARAM,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
13,1,1925,869.0,780.0,702.0,2230.0,7060.0,7020.0,4810.0,3020.0,2360.0,1140.0,894.0,1700.0
14,1,1926,1240.0,857.0,939.0,2710.0,4810.0,4390.0,4300.0,2500.0,1580.0,1450.0,1270.0,882.0
15,1,1927,787.0,633.0,573.0,896.0,3320.0,7360.0,5880.0,3610.0,2510.0,2920.0,1730.0,1030.0
16,1,1928,1050.0,781.0,810.0,1550.0,6470.0,7440.0,5810.0,3230.0,1780.0,1300.0,860.0,540.0
17,1,1929,520.0,497.0,505.0,676.0,2750.0,6180.0,4150.0,2970.0,1890.0,1340.0,986.0,793.0

In [54]:
#changing the format of the dataset to match others
flow = flow_clean.melt(
    id_vars=['PARAM', 'Year'],
    var_name='Month',
    value_name='Discharge'
)
flow.head()

   PARAM  Year Month  Discharge
0      1  1925   Jan      869.0
1      1  1926   Jan     1240.0
2      1  1927   Jan      787.0
3      1  1928   Jan     1050.0
4      1  1929   Jan      520.0

In [55]:
#converting month names to numbers as in other datasets
month_dict = {
    'Jan':1, 'Feb':2, 'Mar':3, 'Apr':4,
    'May':5, 'Jun':6, 'Jul':7, 'Aug':8,
    'Sep':9, 'Oct':10, 'Nov':11, 'Dec':12
}
flow['Month'] = flow['Month'].map(month_dict)